# PHP 8.2 + Apache
FROM php:8.2-apache

# Gerekli bağımlılıkları yükle
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl \
    libzip-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    libwebp-dev \
    libxpm-dev

# PHP extension kurulumları
RUN docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp && \
    docker-php-ext-install \
        pdo \
        pdo_mysql \
        mysqli \
        bcmath \
        gd \
        zip

# Apache mod rewrite aktif et
RUN a2enmod rewrite

# Composer yükle
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# php.ini dosyasını kopyala
COPY ./php.ini /usr/local/etc/php/

# Çalışma dizini
WORKDIR /var/www/html

# Laravel storage ve bootstrap/cache izinleri
RUN mkdir -p /var/www/html/storage /var/www/html/bootstrap/cache
RUN chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache
